version: '3.8'
services:

  server: 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./langteabot/data:/server/data
    build: server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - WEBHOOK_HOST=j1f.ru
      - WEBHOOK_PORT=8443
      - DOCKER_PORT=8443      
      - LANGTEABOT_TOKEN=
      - LANGTEABOT_PORT=4200
      - CALCUBOT_TOKEN=
      - CALCUBOT_PORT=4201
      - HCWBOT_TOKEN=
      - HCWBOT_PORT=4202
      - ID37BOT_TOKEN=

  langteabot:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./langteabot/user_conf:/server/user_conf
      - ./langteabot/logs:/server/logs
    build: langteabot
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - PORT=4200
      - STT_SERVER=ws://localhost:2700
      - TTS_SERVER=http://localhost:10005
      - PHRASE_SEED=

  calcubot:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./calcubot/logs:/app/logs
    build: calcubot
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    dns: 0.0.0.0
    ports:
      - 4201:4201
    environment:
      - TZ=Europe/Moscow
      - PORT=4201

  home_cleaners_watcher_bot:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./home_cleaners_watcher_bot/data:/app/data
    build: home_cleaners_watcher_bot
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    dns: 0.0.0.0
    ports:
      - 4202:4202
    environment:
      - TZ=Europe/Moscow
      - PORT=4202
