version: '3.8'
services:

  server: 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: server
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - WEBHOOK_HOST=j1f.ru
      - WEBHOOK_PORT=443
      - DOCKER_PORT=8443      
      - LANGTEABOT_TOKEN=
      - LANGTEABOT_PORT=4200
      - CALCUBOT_TOKEN=
      - CALCUBOT_PORT=4201

  langteabot:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./langteabot/user_conf:/server/user_conf
      - ./langteabot/logs:/server/logs
    build: langteabot
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - PORT=4200
      - STT_SERVER=ws://localhost:2700
      - TTS_SERVER=http://localhost:10005
      - OPENAI_API_KEY=