version: '3.8'
services:

  server:
    deploy:
      mode: replicated
      replicas: 1    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: server
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - WEBHOOK_HOST=yourhost.name
      - WEBHOOK_PORT=443
      - DOCKER_PORT=8443
      - F37T1BOT_TOKEN=token_of_bot_a
      - LANGTEABOT_TOKEN=token_of_bot_b
      - LANGTEABOT_PORT=4200

  langteabot:
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: langteabot
    ports:
      - 4200:4200
    environment:
      - TZ=Europe/Moscow
      - PORT=4200
      - STT_SERVER=ws://192.168.1.11:2700